---
- name: include arch vars
  include_vars: amd64.yml
  when: ansible_architecture == 'x86_64'

- name: include arch vars
  include_vars: arm.yml
  when: ansible_architecture == 'armv7l'

- name: include arch vars
  include_vars: arm64.yml
  when: ansible_architecture == 'aarch64'

- name: Install Helm
  unarchive:
    src: "https://storage.googleapis.com/kubernetes-helm/helm-{{ helm_version }}-linux-{{ helm_arch }}.tar.gz"
    dest: /usr/local/bin
    extra_opts:
    - --strip=1
    - --wildcards
    - '*/helm'
    remote_src: True

- name: Set Helm binary file mode
  file:
    path: /usr/local/bin/helm
    mode: 0755

- name: Create ServiceAccount for Tiller client
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: tiller
        namespace: kube-system
    validate:
      fail_on_error: yes
      strict: yes

- name: Create ClusterRoleBinding for Tiller Service Account
  k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: tiller-cluster-role
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: tiller
          namespace: kube-system
    validate:
      fail_on_error: yes
      strict: yes

- name: Check if Helm is installed
  command: helm list
  changed_when: False
  failed_when: False
  register: helm_list

- name: Helm init
  command: helm init --upgrade --tiller-image {{ tiller_image }} --service-account tiller --history-max 10 --wait
  when: helm_list.rc != 0
