---
- hosts: edgerouter
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: edgeos
  roles:
  - role: edgerouter_static_hosts
    vars:
      static_hosts: "{{ static_hosts_dict | combine(kvm_hosts_dict | generate_macs) }}"
      networks: "{{ edgerouter_networks }}"
