---
# Master playbook

- hosts: edgerouter
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: edgeos
  roles:
  - role: edgerouter_static_hosts
    vars:
      static_hosts: "{{ static_hosts_dict | combine(kvm_hosts_dict | generate_macs) }}"
      networks: "{{ edgerouter_networks }}"

- hosts: localhost
  tasks:
  - name: add kvm hosts to inventory
    add_host:
      name: "{{ item.key }}"
      groups: kvm
    with_dict: "{{ kvm_hosts_dict }}"

- hosts: kvm
  tasks:
  - name: ping
    ping:
