---
- name: Apply Flannel
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  register: flannel_result
  changed_when: "'created' in flannel_result.stdout"
