- name: haproxy install
  package:
    name: haproxy
    state: present

- name: haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- meta: flush_handlers

- name: haproxy service
  service:
    name: haproxy
    state: started
