---
base_cluster_domain: "{{ ansible_fqdn }}"
api_cluster_domain: "{{ base_cluster_domain }}"
cluster_domain: "apps.{{ base_cluster_domain }}"
cluster_dashes: "{{ cluster_domain | replace('.', '-') }}"
