---
- name: debug
  debug:
    msg: "hosts_map is: {{ hosts_map | type_debug }}"

- name: set hosts_map to dict if string
  set_fact:
    hosts_dict: "{{ hosts_map | from_json }}"
  when: hosts_map | type_debug == 'str'

- name: set hosts_map to dict
  set_fact:
    hosts_dict: "{{ hosts_map }}"

- name: Check variables
  assert:
    that:
      - item.key is defined
      - item.value.ip | ipaddr
      - item.value.mac is regex("^([a-fA-F0-9]{2}[:|\-]?){6}$")
      - item.value.network_name is defined
      - item.value.subnet | ipsubnet
  with_dict: "{{ hosts_map }}"

- name: debugtemplate
  debug:
    msg: "{{ lookup('template', './mappings.j2') }}"

- name: Set the static host and dhcp mapping
  edgeos_config:
    lines: "{{ lookup('template', './mappings.j2') }}"
#    - delete service dhcp-server shared-network-name {{ item.value.network_name }} subnet {{ item.value.subnet }} static-mapping {{ item.key }}
#    - delete system static-host-mapping host-name {{ item.key }}
#    - set service dhcp-server shared-network-name {{ item.value.network_name }} subnet {{ item.value.subnet }} static-mapping {{ item.key }} ip-address {{ item.value.ip }}
#    - set service dhcp-server shared-network-name {{ item.value.network_name }} subnet {{ item.value.subnet }} static-mapping {{ item.key }} mac-address {{ item.value.mac | lower }}
#    - set system static-host-mapping host-name {{ item.key }} inet {{ item.value.ip }}
#  with_dict: "{{ hosts_map }}"
