---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault
  namespace: convlt
spec:
  releaseName: vault
  chart:
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
    name: vault
    version: 0.23.4
  values:
    vault:
      dev: false
      config:
        storage:
          consul:
            address: consul.convlt.svc.cluster.local:8500
            path: vault
    consulAgent:
      join: consul.convlt.svc.cluster.local
      gossipKeySecretName: consul-gossip-key
