---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.27.0
  values:
    controller:
      image:
        repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller-arm64
      hostNetwork: true
      kind: DaemonSet
      daemonset:
        useHostPort: true
        hostPorts:
          http: 80
          https: 443
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      nodeSelector:
        node-role.kubernetes.io/master: ""
    defaultBackend:
      image:
        repository: k8s.gcr.io/defaultbackend-arm64
