---
wireguard_repo_url: "https://copr.fedorainfracloud.org/coprs/jdoss/wireguard/repo/epel-7/jdoss-wireguard-epel-{{ ansible_distribution_major_version }}.repo"
wireguard_repo_gpg_key_url: https://copr-be.cloud.fedoraproject.org/results/jdoss/wireguard/pubkey.gpg
wireguard_repofile_path: /etc/yum.repos.d/wireguard.repo
