---
base_cluster_domain: "{{ ansible_fqdn }}"
api_cluster_domain: "{{ base_cluster_domain }}"
cluster_domain: "apps.{{ base_cluster_domain }}"
cluster_dashes: "{{ cluster_domain | replace('.', '-') }}"

root_ca_issuer_name: selfsigning-issuer-for-root-ca
root_ca_certificate_name: "{{ cluster_dashes }}-root-ca"
root_ca_clusterissuer_name: "{{ cluster_dashes }}-ca-issuer"
