---
- hosts: all
  tasks:
  - name: Slurp private key
    local_action:
      module: slurp
      src: "roles/kubeadm/files/flux_ssh_key"
    register: flux_ssh_key

  - name: Create Flux private ssh key secret
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: testkey
          namespace: flux
        data:
          identity: "{{ flux_ssh_key.content }}"
        type: Opaque
      validate:
        fail_on_error: yes
        strict: yes
#          identity: "{{ lookup('file', 'roles/kubeadm/files/flux_ssh_key') + '\n' | b64encode }}"
